namespace AlgoTradeWithOptimizationSupportWinFormsApp.Trading.Core
{
    /// <summary>
    /// Trading signals generated by strategies
    /// </summary>
    public enum TradeSignals
    {
        None = 0,
        Buy = 1,
        Sell = 2,
        TakeProfit = 3,     // Take Profit
        StopLoss = 4,       // Stop Loss
        Flat = 5,           // Close all positions
        Skip = 6,           // Skip
    }
}
